services:
  app:
    build:
      context: .
      target: production
    container_name: medical-platform-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./requirements.txt:/app/requirements.txt
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./medical_platform.db
      - MAX_FILE_SIZE=52428800
      - MIN_PROCESSING_TIME=5
      - MAX_PROCESSING_TIME=20
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s