services:
  app:
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    container_name: medical-platform-api-dev
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app
      - ../backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./medical_platform.db 
      - MAX_FILE_SIZE=52428800
      - MIN_PROCESSING_TIME=5
      - MAX_PROCESSING_TIME=20
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped